# -*- coding: utf-8 -*-
"""face_detection_3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ilhp_WttZmEAgAywYRtdIfFP2gjqzrr8
"""

import imutils
import numpy as np
import cv2
#from google.colab import files
import requests

def download_models():
    # Download the pre-trained face detection models
    prototxt_url = 'https://raw.githubusercontent.com/opencv/opencv/master/samples/dnn/face_detector/deploy.prototxt'
    model_url = 'https://raw.githubusercontent.com/opencv/opencv_3rdparty/dnn_samples_face_detector_20170830/res10_300x300_ssd_iter_140000.caffemodel'
    with open('deploy.prototxt', 'wb') as f:
        f.write(requests.get(prototxt_url).content)
    with open('res10_300x300_ssd_iter_140000.caffemodel', 'wb') as f:
        f.write(requests.get(model_url).content)

def detect_face(image_file):
    download_models()

    file_bytes = np.asarray(bytearray(image_file.read()), dtype=np.uint8)
    image = cv2.imdecode(file_bytes, 1)

    # Read and resize the uploaded image
    #image = cv2.imread(image_file)
    image = imutils.resize(image, width=400)
    #(h, w) = image.shape[:2]

    # Load the pre-trained face detection model
    prototxt = 'deploy.prototxt'
    model = 'res10_300x300_ssd_iter_140000.caffemodel'
    net = cv2.dnn.readNetFromCaffe(prototxt, model)

    # Construct a blob from the image and pass it through the neural network
    blob = cv2.dnn.blobFromImage(cv2.resize(image, (300, 300)), 1.0, (300, 300), (104.0, 177.0, 123.0))
    net.setInput(blob)
    detections = net.forward()

    # Check if a face is detected
    face_detected = False
    for i in range(0, detections.shape[2]):
        confidence = detections[0, 0, i, 2]
        if confidence > 0.5:
            face_detected = True
            break

    # Return 1 if face detected, 0 otherwise
    return 1 if face_detected else 0

    # Download the face detection models
    #download_models()

    # Upload an image file
    #uploaded = files.upload()
    #image_file = list(uploaded.keys())[0]

    # Call the detect_face method and print the result
    #result = detect_face(image_file)
    #return result

# Call the face_detection method to run the face detection process
#result = face_detection()
#print(result)

